name: flutter_animated_navkit
description: A customizable animated bottom navigation bar with expandable hexagonal notch for Flutter apps.
version: 1.0.0
license: MIT

homepage: https://github.com/Raj3448/flutter_animated_navkit
repository: https://github.com/Raj3448/flutter_animated_navkit
issue_tracker: https://github.com/Raj3448/flutter_animated_navkit/issues
documentation: https://github.com/Raj3448/flutter_animated_navkit#readme

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hexagon: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # No assets/fonts declared yet
